### ISSUE TITLE
Create A Fun Python Script

### ISSUE THREAD

**Issue by sid-am-ahd935** [sid-am-ahd935/Aliahns#1]

**Comment by sid-am-ahd935** [comment]
Create a code snippet written in python consisting more than 40 lines of code.

**Comment by Pratham16121** [comment]
Can you assign me this?

**Comment by haris-bit** [comment]
I'll create a password generator using Python

**Comment by sid-am-ahd935** [comment]
> I'll create a password generator using Python

Create a new issue, I will add the labels

**Comment by Pratham16121** [comment]
[](url)

> > Can you assign me this?
> 
> @Pratham16121 Can you give me some insights of what you are planning to create?

I have an idea to make a sudoku game. Controlling with arrow keys. With correct moves and wrong moves

**Comment by sid-am-ahd935** [comment]
Ok @Pratham16121 I am assigning you this issue, make sure to name files accordingly and add the files in the appropriate folder.

**Comment by Pratham16121** [comment]
@sid-am-ahd935 Can you add topic "hacktoberfest" and a label "hacktoberfest-accepted" in all the issues?

**Comment by sid-am-ahd935** [comment]
@Pratham16121 hacktoberfest-accepted label is when you have completed the issue.
Remaining issues have been added the required labels.

**Comment by haris-bit** [comment]
@sid-am-ahd935 I created the issue. Here's the link: https://github.com/sid-am-ahd935/Aliahns/issues/5

**Comment by haris-bit** [comment]
Don't you need to assign me anything in order for me to send a pull request to the repo?

**Comment by sid-am-ahd935** [comment]
@haris-bit check that issue

**Comment by MadScientist46290** [comment]
I wanna make conway's game of llife, please assign me this issue

**Comment by sid-am-ahd935** [comment]
@MadScientist46290  Please create new issue for this

**Comment by haris-bit** [comment]
@sid-am-ahd935 I sent a pull request for my python password generator script
