### ISSUE TITLE
Hangman game using Python

### ISSUE THREAD

**Issue by vilasrhegde** [sid-am-ahd935/Aliahns#13]

**Comment by sid-am-ahd935** [comment]
@vilasrhegde Assigning you this issue

**Comment by vilasrhegde** [comment]
Thank you

**Comment by neutr0n420** [comment]
can I work on this issue?

**Comment by sid-am-ahd935** [comment]
> can I work on this issue?

Hi @neutr0n420 please open a new issue for another idea, this has already been completed.
