### ISSUE TITLE
Create a Rock, Paper, Scissor game in Python

### ISSUE THREAD

**Issue by RitamPaul** [sid-am-ahd935/Aliahns#15]

**Comment by sid-am-ahd935** [comment]
First make sure to read the contribution guidelines inside the Python folder and confirm if you are able to complete complete this issue or not.

**Comment by thunderstormO1** [comment]
Hey Sid I think I can contribute to this issue , can you assign this issue to me?

**Comment by RitamPaul** [comment]
Yes aman bro, i want to upload a simple game of rock-paper-scissor
it will be a .py file
it will be very helpful if you kindly instruct me how to name the folder
and file

**Comment by sid-am-ahd935** [comment]
Hi @RitamPaul sorry for being late, after cloning the repo, 

- Create a new folder in Python (your chosen language)
- Add the program file you have created, the folder name and the file name could be the same.
- Create a README.md file inside your new folder and add a brief description of your program as well as a screenshot of your code running with its output and all.
- Make sure to follow our guidelines of keeping code more than 40 lines.
- And do not edit any other file except for your own folder.

I think this should be enough, if you still have any doubts reply to this message.

**Comment by sid-am-ahd935** [comment]
> Hey Sid I think I can contribute to this issue , can you assign this issue to me?

Hi @thunderstormO1 you can create a new issue with some other program idea you have. This issue is created by @RitamPaul .

**Comment by sid-am-ahd935** [comment]
Hey @RitamPaul  any updates on the issue?

**Comment by RitamPaul** [comment]
Yes bhaiya, i have done the project. Can i send you in whatsapp at first ?

**Comment by sid-am-ahd935** [comment]
Sure
