### ISSUE TITLE
Create a Password generator program using Python.

### ISSUE THREAD

**Issue by haris-bit** [sid-am-ahd935/Aliahns#16]

**Comment by sid-am-ahd935** [comment]
I have checked your pull request. Please read the comments added there.

**Comment by sona-123** [comment]
@sid-am-ahd935 Sir Can you please assign this issue to me to work under hacktoberfest

**Comment by sid-am-ahd935** [comment]
@sona-123 I am sorry but this issue is already taken up. Please create a new issue and read the guidelines in the appropriate language folders to understand how to contribute in this repo.
