### ISSUE TITLE
cpp: basic m×n matrix template library

### ISSUE THREAD

**Issue by AvirukBasak** [sid-am-ahd935/Aliahns#18]
### Features
- creating a zero matrix of given size
- creating a unit matrix of given size
- get
- set
- equals
- addition
- subtraction
- scalar multiplication
- matrix multiplication
- power
- overloaded operators
- determinant
- transpose
- cofactor
- adjoint
- inverse
- print

**Comment by sid-am-ahd935** [comment]
You may start working on this issue now @AvirukBasak.

**Comment by AvirukBasak** [comment]
thanks
