### ISSUE TITLE
Create a Tic-Tac-Toe game in Python

### ISSUE THREAD

**Issue by NNRepos** [sid-am-ahd935/Aliahns#19]
hi @sid-am-ahd935 , i would like to add this game.
please assign me and i will create a PR 😄

**Comment by sid-am-ahd935** [comment]
Please read the contribution guidelines in Python folder and confirm your issue update.

**Comment by NNRepos** [comment]
hello, are you talking about `Python/README.md`? i only see guidelines related to the PR, not the issue.
am i missing something?

**Comment by sid-am-ahd935** [comment]
Sorry for being late, yeah about the Python/README.md, did you get what is asked in there?
Just that:

- Python code should be above 40 lines
- Create a new folder to add your program, add a small README.md for that program and add a screenshot of your code running in there.
- Do not edit any other files.

**Comment by sid-am-ahd935** [comment]
I am assigning you this issue. All the best.
