### ISSUE TITLE
Create A Fun C++ Script

### ISSUE THREAD

**Issue by sid-am-ahd935** [sid-am-ahd935/Aliahns#2]
Create a code snippet in the appropriate folders using C++ of more than 60 lines of code

**Comment by Nandini2806** [comment]
@sid-am-ahd935 I am planning to make tic-tac-toe using c++, so please assign me this issue

**Comment by sid-am-ahd935** [comment]
Ok @Nandini2806, please follow the guidelines inside the C++ folder.

**Comment by Nandini2806** [comment]
@sid-am-ahd935 Raised PR for Tic-tac-toe. Do see it!

**Comment by sid-am-ahd935** [comment]
Hi @Nandini2806 please check the updates requested in the PR.

**Comment by Nandini2806** [comment]
Hi @sid-am-ahd935 , done the changes! Please verify
