### ISSUE TITLE
VARIOUS PATTERNS IN C++ 

### ISSUE THREAD

**Issue by A-R-M-028** [sid-am-ahd935/Aliahns#23]
Hey I want to contribute in your repo (c++ section) with some interesting patterns which is really amazing.
Please tell me shall I go ahead with it or not?

**Comment by sid-am-ahd935** [comment]
Yes you can go ahead @A-R-M-028.

- Create your own folder inside C++ folder
- Add your programs there.
- More than 60 lines of code base is needed to be eligible for accepted submission
- Add a README.md inside your folder to explain briefly about your codebase and add some screenshots as well.
- Do not edit any other file.

I am assinging you this issue, Good Luck!

**Comment by A-R-M-028** [comment]
_Ok thanks & please add the Hactoberfest label..._
