### ISSUE TITLE
Random password generator in java

### ISSUE THREAD

**Issue by FaiyazUllah786** [sid-am-ahd935/Aliahns#27]
Generate OTP for different platforms authentication

**Comment by sid-am-ahd935** [comment]
Please specify what language you will be using and also read the contribution guidelines for the same.

**Comment by FaiyazUllah786** [comment]
Random password generator in java language

**Comment by FaiyazUllah786** [comment]
Did you merge it?

**Comment by sid-am-ahd935** [comment]
Hi @FaiyazUllah786 I had commented in your PR have you checked it?

**Comment by sid-am-ahd935** [comment]
Hi @FaiyazUllah786 you can definitely create a new issue if you feel like, or edit this issue here only and make some changes in your old PR only to decrease latency.

**Comment by shivu2002a** [comment]
Can you assign me this issue?

**Comment by sid-am-ahd935** [comment]
Hi @shivu2002a I am assigning you this issue, please read the read the contributions guidelines inside each languages folder...

**Comment by shivu2002a** [comment]
Sure
