### ISSUE TITLE
Decorate the README.md file in this repository

### ISSUE THREAD

**Issue by sid-am-ahd935** [sid-am-ahd935/Aliahns#4]
The edit should contain a minimum of 20 line difference or at least 5 additional features such as images, links, badges, etc.

**Comment by sid-am-ahd935** [comment]
The edit should contain a minimum of 20 line difference or at least 5 additional features such as images, links, badges, etc.

**Comment by recksoldier** [comment]
I would like to contribute!

**Comment by sid-am-ahd935** [comment]
@recksoldier Assigning you this issue

**Comment by sid-am-ahd935** [comment]
Hi @varunsood2003 you can create a new issue for any program that you want to add in this repository. If you have no knowledge in coding, you can create an issue for updating all the "README.md" files in the various folders for more decorations.
