### ISSUE TITLE
Add new features to C++/libmatrix

### ISSUE THREAD

**Issue by AvirukBasak** [sid-am-ahd935/Aliahns#40]
#### Overload operator [ ]
Enables following syntax
```c++
matrix<int> m(5, 5);
m[2][3] = 11;
```

#### Constructor for 2D std::initializer_list
Enables following syntax
```c++
matrix<int> m2 {
    { 0, 2, 3, 4 },
    { 7, 1, 5, 6 },
    { 6, 5, 2, 7 },
    { 4, 3, 2, 3 }
};
```

#### Disable default constructor
Makes sure a matrix always has its attributes (dimensions and data) defined.

This eliminates need to check a matrix for a nullptr attribute.
```c++
matrix<int> m;    // error
```

####  Excess features
1. Reference counter for smart memory management.
2. Overload `=` and add copy constructor.

**Comment by AvirukBasak** [comment]
> Hi @AvirukBasak is this an enhancement for the library/header file you had already uploaded in your previous PR?

Yup

**Comment by sid-am-ahd935** [comment]
Ok, I am adding the necessary labels, you may start working on this issue.
