### ISSUE TITLE
Age calculator in javascript 

### ISSUE THREAD

**Issue by MohsinKing2002** [sid-am-ahd935/Aliahns#45]
@sid-am-ahd935  please assign it to me

**Comment by sid-am-ahd935** [comment]
Hi @MohsinKing2002 assigning you this issue.

**Comment by Aishaa-26** [comment]
@sid-am-ahd935 Please assign this issue to me. I would like to work on it.

**Comment by sid-am-ahd935** [comment]
Hi @Aishaa-26 you can create a new issue and I will assign it to you, this issue was already assigned and has been resolved now.
