### ISSUE TITLE
Python Password Generator Script

### ISSUE THREAD

**Issue by haris-bit** [sid-am-ahd935/Aliahns#5]
Code is below:

import random

print('Welcome to Your Password Generator')

chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()_+0123456789'

number = input('Amount of Passwords to Generate: ')
number = int(number)

length = input('Input your password length: ')
length = int(length)

print('\nHere are your passwords:')

for pwd in range(number):
    password = ''
    for c in range(length):
        password += random.choice(chars)
    print(password)

**Comment by sid-am-ahd935** [comment]
Don't write your code here. Remove this comment. Create a new issue with heading "Create a Password generator program using Python." And Read the guidelines given in the folder before submitting the pull request.

Also add your code in the respective folders.

**Comment by sid-am-ahd935** [comment]
> Don't write your code here. Remove this comment. Create a new issue with heading "Create a Password generator program using Python." And Read the guidelines given in the folder before submitting the pull request.
> 
> Also add your code in the respective folders.

@haris-bit

**Comment by haris-bit** [comment]
ok, done.
I sent a pull request to your repo.
![image](https://user-images.githubusercontent.com/59412623/194580956-7538ca83-2a78-4325-85da-b53bc3f2cdf8.png)
