### ISSUE TITLE
Weather Status Any City

### ISSUE THREAD

**Issue by asmallick1999** [sid-am-ahd935/Aliahns#9]
Using HTML, CSS, Bootstrap, Vanilla JS, API

**Comment by sid-am-ahd935** [comment]
@asmallick1999 Assigning you this issue

**Comment by sid-am-ahd935** [comment]
Hi @asmallick1999 any updates on this issue?

**Comment by sid-am-ahd935** [comment]
Hi @asmallick1999 any updates on this issue?

**Comment by MohsinKing2002** [comment]
@sid-am-ahd935 is this issue solved ?
otherwise assign it to me please

**Comment by AsifStar786** [comment]
@sid-am-ahd935 You can assign it to me also....

**Comment by AsifStar786** [comment]
@sid-am-ahd935 is it now available ??
Can I make a pull request..
